INSERT INTO disease(ICD,disease_name) VALUES
('E6601','Morbid (severe) obesity due to excess calories'),
('F310','Bipolar disorder, current episode hypomanic'),
('F3110','Bipolar disorder, current episode manic without psychotic features, unspecified'),
('F3111','Bipolar disorder, current episode manic without psychotic features, mild'),
('F3112','Bipolar disorder, current episode manic without psychotic features, moderate'),
('F3113','Bipolar disorder, current episode manic without psychotic features, severe'),
('F320','Major depressive disorder, single episode, mild'),
('F321','Major depressive disorder, single episode, moderate'),
('F322','Major depressive disorder, single episode, severe without psychotic features'),
('F323','Major depressive disorder, single episode, severe with psychotic features'),
('F324','Major depressive disorder, single episode, in partial remission'),
('F325','Major depressive disorder, single episode, in full remission'),
('F3289','Other specified depressive episodes'),
('F329','Major depressive disorder, single episode, unspecified'),
('F32A','Depression, unspecified'),
('F330','Major depressive disorder, recurrent, mild'),
('F331','Major depressive disorder, recurrent, moderate'),
('F332','Major depressive disorder, recurrent severe without psychotic features'),
('F333','Major depressive disorder, recurrent, severe with psychotic symptoms'),
('G43001','Migraine without aura, not intractable, with status migrainosus'),
('G4700','Insomnia, unspecified'),
('J4520','Mild intermittent asthma, uncomplicated'),
('K08101','Complete loss of teeth, unspecified cause, class I'),
('K08102','Complete loss of teeth, unspecified cause, class II'),
('K08103','Complete loss of teeth, unspecified cause, class III'),
('K08104','Complete loss of teeth, unspecified cause, class IV'),
('K08109','Complete loss of teeth, unspecified cause, unspecified class'),
('K08111','Complete loss of teeth due to trauma, class I'),
('K08112','Complete loss of teeth due to trauma, class II'),
('K08113','Complete loss of teeth due to trauma, class III'),
('K08114','Complete loss of teeth due to trauma, class IV'),
('K08119','Complete loss of teeth due to trauma, unspecified class'),
('K08401','Partial loss of teeth, unspecified cause, class I'),
('K08402','Partial loss of teeth, unspecified cause, class II'),
('K08403','Partial loss of teeth, unspecified cause, class III'),
('K08404','Partial loss of teeth, unspecified cause, class IV'),
('K08409','Partial loss of teeth, unspecified cause, unspecified class'),
('K08411','Partial loss of teeth due to trauma, class I'),
('K08412','Partial loss of teeth due to trauma, class II'),
('K08413','Partial loss of teeth due to trauma, class III'),
('K08414','Partial loss of teeth due to trauma, class IV'),
('K08419','Partial loss of teeth due to trauma, unspecified class'),
('M5450','Low back pain, unspecified'),
('M5459','Other low back pain'),
('M60000','Infective myositis, unspecified right arm'),
('M60001','Infective myositis, unspecified left arm'),
('M60002','Infective myositis, unspecified arm'),
('M60003','Infective myositis, unspecified right leg'),
('M60004','Infective myositis, unspecified left leg'),
('M60005','Infective myositis, unspecified leg'),
('M60009','Infective myositis, unspecified site'),
('M60011','Infective myositis, right shoulder'),
('M60012','Infective myositis, left shoulder'),
('M60019','Infective myositis, unspecified shoulder'),
('M60021','Infective myositis, right upper arm'),
('M60022','Infective myositis, left upper arm'),
('M60029','Infective myositis, unspecified upper arm'),
('M60031','Infective myositis, right forearm'),
('M60032','Infective myositis, left forearm'),
('M60039','Infective myositis, unspecified forearm'),
('M60041','Infective myositis, right hand'),
('M60042','Infective myositis, left hand'),
('M60043','Infective myositis, unspecified hand'),
('M60044','Infective myositis, right finger(s)'),
('M60045','Infective myositis, left finger(s)'),
('M60046','Infective myositis, unspecified finger(s)'),
('M60051','Infective myositis, right thigh'),
('M60052','Infective myositis, left thigh'),
('M60059','Infective myositis, unspecified thigh'),
('M60061','Infective myositis, right lower leg'),
('M60062','Infective myositis, left lower leg'),
('M60069','Infective myositis, unspecified lower leg'),
('M60070','Infective myositis, right ankle'),
('M60071','Infective myositis, left ankle'),
('M60072','Infective myositis, unspecified ankle'),
('M60073','Infective myositis, right foot'),
('M60074','Infective myositis, left foot'),
('M60075','Infective myositis, unspecified foot'),
('M60076','Infective myositis, right toe(s)'),
('M60077','Infective myositis, left toe(s)'),
('M60078','Infective myositis, unspecified toe(s)'),
('M6008','Infective myositis, other site'),
('M6009','Infective myositis, multiple sites'),
('M6080','Other myositis, unspecified site'),
('M60811','Other myositis, right shoulder'),
('M60812','Other myositis, left shoulder'),
('M60819','Other myositis, unspecified shoulder'),
('M60821','Other myositis, right upper arm'),
('M60822','Other myositis, left upper arm'),
('M60829','Other myositis, unspecified upper arm'),
('M60831','Other myositis, right forearm'),
('M60832','Other myositis, left forearm'),
('M60839','Other myositis, unspecified forearm'),
('M60841','Other myositis, right hand'),
('M60842','Other myositis, left hand'),
('M60849','Other myositis, unspecified hand'),
('M60851','Other myositis, right thigh'),
('M60852','Other myositis, left thigh'),
('M60859','Other myositis, unspecified thigh'),
('M60861','Other myositis, right lower leg'),
('M60862','Other myositis, left lower leg'),
('M60869','Other myositis, unspecified lower leg'),
('M60871','Other myositis, right ankle and foot'),
('M60872','Other myositis, left ankle and foot'),
('M60879','Other myositis, unspecified ankle and foot'),
('M6088','Other myositis, other site'),
('M6089','Other myositis, multiple sites'),
('R5083','Postvaccination fever'),
('R509','Fever, unspecified'),
('R519','Headache, unspecified'),
('R531','Weakness'),
('Z20822','Contact with and (suspected) exposure to COVID-19');
