INSERT INTO disease(ICD,disease_name) VALUES ('E6601','Morbid (severe) obesity due to excess calories');
INSERT INTO disease(ICD,disease_name) VALUES ('F310','Bipolar disorder, current episode hypomanic');
INSERT INTO disease(ICD,disease_name) VALUES ('F3110','Bipolar disorder, current episode manic without psychotic features, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('F3111','Bipolar disorder, current episode manic without psychotic features, mild');
INSERT INTO disease(ICD,disease_name) VALUES ('F3112','Bipolar disorder, current episode manic without psychotic features, moderate');
INSERT INTO disease(ICD,disease_name) VALUES ('F3113','Bipolar disorder, current episode manic without psychotic features, severe');
INSERT INTO disease(ICD,disease_name) VALUES ('F320','Major depressive disorder, single episode, mild');
INSERT INTO disease(ICD,disease_name) VALUES ('F321','Major depressive disorder, single episode, moderate');
INSERT INTO disease(ICD,disease_name) VALUES ('F322','Major depressive disorder, single episode, severe without psychotic features');
INSERT INTO disease(ICD,disease_name) VALUES ('F323','Major depressive disorder, single episode, severe with psychotic features');
INSERT INTO disease(ICD,disease_name) VALUES ('F324','Major depressive disorder, single episode, in partial remission');
INSERT INTO disease(ICD,disease_name) VALUES ('F325','Major depressive disorder, single episode, in full remission');
INSERT INTO disease(ICD,disease_name) VALUES ('F3289','Other specified depressive episodes');
INSERT INTO disease(ICD,disease_name) VALUES ('F329','Major depressive disorder, single episode, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('F32A','Depression, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('F330','Major depressive disorder, recurrent, mild');
INSERT INTO disease(ICD,disease_name) VALUES ('F331','Major depressive disorder, recurrent, moderate');
INSERT INTO disease(ICD,disease_name) VALUES ('F332','Major depressive disorder, recurrent severe without psychotic features');
INSERT INTO disease(ICD,disease_name) VALUES ('F333','Major depressive disorder, recurrent, severe with psychotic symptoms');
INSERT INTO disease(ICD,disease_name) VALUES ('G43001','Migraine without aura, not intractable, with status migrainosus');
INSERT INTO disease(ICD,disease_name) VALUES ('G4700','Insomnia, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('J4520','Mild intermittent asthma, uncomplicated');
INSERT INTO disease(ICD,disease_name) VALUES ('K08101','Complete loss of teeth, unspecified cause, class I');
INSERT INTO disease(ICD,disease_name) VALUES ('K08102','Complete loss of teeth, unspecified cause, class II');
INSERT INTO disease(ICD,disease_name) VALUES ('K08103','Complete loss of teeth, unspecified cause, class III');
INSERT INTO disease(ICD,disease_name) VALUES ('K08104','Complete loss of teeth, unspecified cause, class IV');
INSERT INTO disease(ICD,disease_name) VALUES ('K08109','Complete loss of teeth, unspecified cause, unspecified class');
INSERT INTO disease(ICD,disease_name) VALUES ('K08111','Complete loss of teeth due to trauma, class I');
INSERT INTO disease(ICD,disease_name) VALUES ('K08112','Complete loss of teeth due to trauma, class II');
INSERT INTO disease(ICD,disease_name) VALUES ('K08113','Complete loss of teeth due to trauma, class III');
INSERT INTO disease(ICD,disease_name) VALUES ('K08114','Complete loss of teeth due to trauma, class IV');
INSERT INTO disease(ICD,disease_name) VALUES ('K08119','Complete loss of teeth due to trauma, unspecified class');
INSERT INTO disease(ICD,disease_name) VALUES ('K08401','Partial loss of teeth, unspecified cause, class I');
INSERT INTO disease(ICD,disease_name) VALUES ('K08402','Partial loss of teeth, unspecified cause, class II');
INSERT INTO disease(ICD,disease_name) VALUES ('K08403','Partial loss of teeth, unspecified cause, class III');
INSERT INTO disease(ICD,disease_name) VALUES ('K08404','Partial loss of teeth, unspecified cause, class IV');
INSERT INTO disease(ICD,disease_name) VALUES ('K08409','Partial loss of teeth, unspecified cause, unspecified class');
INSERT INTO disease(ICD,disease_name) VALUES ('K08411','Partial loss of teeth due to trauma, class I');
INSERT INTO disease(ICD,disease_name) VALUES ('K08412','Partial loss of teeth due to trauma, class II');
INSERT INTO disease(ICD,disease_name) VALUES ('K08413','Partial loss of teeth due to trauma, class III');
INSERT INTO disease(ICD,disease_name) VALUES ('K08414','Partial loss of teeth due to trauma, class IV');
INSERT INTO disease(ICD,disease_name) VALUES ('K08419','Partial loss of teeth due to trauma, unspecified class');
INSERT INTO disease(ICD,disease_name) VALUES ('M5450','Low back pain, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('M5459','Other low back pain');
INSERT INTO disease(ICD,disease_name) VALUES ('M60000','Infective myositis, unspecified right arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60001','Infective myositis, unspecified left arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60002','Infective myositis, unspecified arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60003','Infective myositis, unspecified right leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60004','Infective myositis, unspecified left leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60005','Infective myositis, unspecified leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60009','Infective myositis, unspecified site');
INSERT INTO disease(ICD,disease_name) VALUES ('M60011','Infective myositis, right shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60012','Infective myositis, left shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60019','Infective myositis, unspecified shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60021','Infective myositis, right upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60022','Infective myositis, left upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60029','Infective myositis, unspecified upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60031','Infective myositis, right forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60032','Infective myositis, left forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60039','Infective myositis, unspecified forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60041','Infective myositis, right hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60042','Infective myositis, left hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60043','Infective myositis, unspecified hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60044','Infective myositis, right finger(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M60045','Infective myositis, left finger(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M60046','Infective myositis, unspecified finger(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M60051','Infective myositis, right thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60052','Infective myositis, left thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60059','Infective myositis, unspecified thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60061','Infective myositis, right lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60062','Infective myositis, left lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60069','Infective myositis, unspecified lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60070','Infective myositis, right ankle');
INSERT INTO disease(ICD,disease_name) VALUES ('M60071','Infective myositis, left ankle');
INSERT INTO disease(ICD,disease_name) VALUES ('M60072','Infective myositis, unspecified ankle');
INSERT INTO disease(ICD,disease_name) VALUES ('M60073','Infective myositis, right foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M60074','Infective myositis, left foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M60075','Infective myositis, unspecified foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M60076','Infective myositis, right toe(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M60077','Infective myositis, left toe(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M60078','Infective myositis, unspecified toe(s)');
INSERT INTO disease(ICD,disease_name) VALUES ('M6008','Infective myositis, other site');
INSERT INTO disease(ICD,disease_name) VALUES ('M6009','Infective myositis, multiple sites');
INSERT INTO disease(ICD,disease_name) VALUES ('M6080','Other myositis, unspecified site');
INSERT INTO disease(ICD,disease_name) VALUES ('M60811','Other myositis, right shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60812','Other myositis, left shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60819','Other myositis, unspecified shoulder');
INSERT INTO disease(ICD,disease_name) VALUES ('M60821','Other myositis, right upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60822','Other myositis, left upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60829','Other myositis, unspecified upper arm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60831','Other myositis, right forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60832','Other myositis, left forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60839','Other myositis, unspecified forearm');
INSERT INTO disease(ICD,disease_name) VALUES ('M60841','Other myositis, right hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60842','Other myositis, left hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60849','Other myositis, unspecified hand');
INSERT INTO disease(ICD,disease_name) VALUES ('M60851','Other myositis, right thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60852','Other myositis, left thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60859','Other myositis, unspecified thigh');
INSERT INTO disease(ICD,disease_name) VALUES ('M60861','Other myositis, right lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60862','Other myositis, left lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60869','Other myositis, unspecified lower leg');
INSERT INTO disease(ICD,disease_name) VALUES ('M60871','Other myositis, right ankle and foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M60872','Other myositis, left ankle and foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M60879','Other myositis, unspecified ankle and foot');
INSERT INTO disease(ICD,disease_name) VALUES ('M6088','Other myositis, other site');
INSERT INTO disease(ICD,disease_name) VALUES ('M6089','Other myositis, multiple sites');
INSERT INTO disease(ICD,disease_name) VALUES ('R5083','Postvaccination fever');
INSERT INTO disease(ICD,disease_name) VALUES ('R509','Fever, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('R519','Headache, unspecified');
INSERT INTO disease(ICD,disease_name) VALUES ('R531','Weakness');
INSERT INTO disease(ICD,disease_name) VALUES ('Z20822','Contact with and (suspected) exposure to COVID-19');
