INSERT INTO category(category_id,category) VALUES
(0,'Allergist'),
(1,'Anesthesiologist'),
(2,'Cardiologist'),
(3,'Critical Care Medicine Specialist'),
(4,'Dermatologist'),
(5,'Endocrinologist'),
(6,'Family Physician'),
(7,'Gastroenterologist'),
(8,'Geriatric Medicine Specialist'),
(9,'Hematologist'),
(10,'Hospice and Palliative Medicine Specialist'),
(11,'Infectious Disease Specialist'),
(12,'Internist'),
(13,'Medical Geneticist'),
(14,'Nephrologist'),
(15,'Neurologist'),
(16,'Obstetrician'),
(17,'Oncologist'),
(18,'Ophthalmologist'),
(19,'Osteopath'),
(20,'Otolaryngologist'),
(21,'Pediatrician'),
(22,'Physiatrist'),
(23,'Plastic Surgeon'),
(24,'Podiatrist'),
(25,'Preventive Medicine Specialist'),
(26,'Psychiatrist'),
(27,'Pulmonologist'),
(28,'Radiologist'),
(29,'Rheumatologist'),
(30,'Sleep Medicine Specialist'),
(31,'Sports Medicine Specialist'),
(32,'General Surgeon'),
(33,'Urologist');
